version: '3'

services:
  crafty:
    container_name: Stoneblock
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Etc/UTC
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "22667:25565" # MC SERV PORT
    volumes:
        - /srv/docker/crafty-stoneblock/backups:/crafty/backups
        - /srv/docker/crafty-stoneblock/logs:/crafty/logs
        - /srv/docker/crafty-stoneblock/servers:/crafty/servers
        - /srv/docker/crafty-stoneblock/config:/crafty/app/config
        - /srv/docker/crafty-stoneblock/import:/crafty/import
