services:
    404-a:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "38635:8080"
        environment:
            TEMPLATE_NAME: app-down
    404-b:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "19318:8080"
        environment:
            TEMPLATE_NAME: cats
    404-c:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "45024:8080"
        environment:
            TEMPLATE_NAME: connection
    404-d:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "61396:8080"
        environment:
            TEMPLATE_NAME: ghost
    404-e:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "20664:8080"
        environment:
            TEMPLATE_NAME: hacker-terminal
    404-f:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "53516:8080"
        environment:
            TEMPLATE_NAME: l7
    404-g:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "11723:8080"
        environment:
            TEMPLATE_NAME: lost-in-space
    404-h:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "48057:8080"
        environment:
            TEMPLATE_NAME: noise
    404-i:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "29826:8080"
        environment:
            TEMPLATE_NAME: orient
    404-j:
        image: ghcr.io/tarampampam/error-pages
        ports: 
            - "58553:8080"
        environment:
            TEMPLATE_NAME: shuffle