services:
  bungeecord:
    image: itzg/mc-proxy:java21
    environment:
      TYPE: BUNGEECORD
    ports:
      - "22665:25565"
    networks:
      - babymc
    volumes:
      - "/srv/docker/minecraft/babymc/bungeecord:/server"
  lobby:
    image: itzg/minecraft-server:java21
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "22666"
    networks:
      - babymc
    volumes:
      - 
  island:
    image: itzg/minecraft-server:java21
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25567"
    networks:
      - babymc
    volumes:
      -  
  skyblock:
    image: itzg/minecraft-server:java21
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25568"
    networks:
      - babymc
    volumes:
      - 
  zoo:
    image: itzg/minecraft-server:java21
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25569"
    networks:
      - babymc
    volumes:
      - 

networks:
  babymc:
    name: babymc