services:
  bungeecord:
    image: itzg/mc-proxy:java17
    environment:
      TYPE: BUNGEECORD
    ports:
      - "22665:25565"
    networks:
      - babymc
    volumes:
      - "/srv/docker/minecraft/babymc/bungeecord:/server"
  lobby:
    image: itzg/minecraft-server:java17
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25566:25565"
    networks:
      - babymc
    volumes:
      - "/srv/docker/minecraft/babymc/lobby:/data"
  island:
    image: itzg/minecraft-server:java17
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25567:25565"
    networks:
      - babymc
    volumes:
      -  "/srv/docker/minecraft/babymc/island:/data"
  skyblock:
    image: itzg/minecraft-server:java17
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25568:25565"
    networks:
      - babymc
    volumes:
      - "/srv/docker/minecraft/babymc/skyblock:/data"
  zoo:
    image: itzg/minecraft-server:java17
    environment:
      EULA: true
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
    ports:
      - "25569:25565"
    networks:
      - babymc
    volumes:
      - "/srv/docker/minecraft/babymc/zoo:/data"

networks:
  babymc:
    name: babymc