version: '3'

services:
  crafty:
    container_name: Grind
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Etc/UTC
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "25565:25565" # MC SERV PORT
    volumes:
        - /srv/docker/crafty-grind/backups:/crafty/backups
        - /srv/docker/crafty-grind/logs:/crafty/logs
        - /srv/docker/crafty-grind/servers:/crafty/servers
        - /srv/docker/crafty-grind/config:/crafty/app/config
        - /srv/docker/crafty-grind/import:/crafty/import
