services:
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    restart: always
    environment:
      # enable API
      API_BINDING: ":25564"
      DEBUG: true
      MAPPING: |
        babymc.naftali.xyz=10.255.65.1:22665
        babymc.silvera.win=10.255.65.1:22665
        playmc.naftali.xyz=172.20.41.3:29913
        playmc.silvera.win=172.20.41.3:29913
        modmc.naftali.xyz=172.20.41.4:62955
        modmc.silvera.win=172.20.41.4:62955
        grind.naftali.xyz=172.20.41.5:52210
        grind.silvera.win=172.20.41.5:52210
    ports:
      - "25565:25565"
      # bind the API port to only loopback to avoid external exposure
      - "127.0.0.1:25564:25564"
